print("\t-----------------------------------------")
print("\t|\t PHONES   \t\t\t|")
print("\t|\t\t\t\t\t|")
print("\t| Name:\tREDMI NOTE9\t\t\t|")
print("\t| Colour:\tblue\t\t\t|")
print("\t| Manufacturer:\tXiamoi\t\t\t|")
print("\t| Brand:\tRedmi/POCO \t\t|")
print("\t-----------------------------------------")